version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: keycloak_db
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080/tcp"
    command: start-dev --http-port=8080
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: mysql
      DB_ADDR: jdbc:mysql://mysql:3306/keycloak_db
      DB_USER: admin
      DB_PASSWORD: admin

# для последней версии
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#      KC_DB: mysql
#      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak_db
#      KC_DB_USERNAME: admin
#      KC_DB_PASSWORD: admin
    depends_on:
      mysql:
        condition: "service_started"

    networks:
      - keycloak-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak-and-mysql-volume:
