FROM quay.io/keycloak/keycloak:26.0.8

COPY --from=mysql:8.0 /usr/bin/mysqladmin /usr/bin/mysqladmin
COPY --from=mysql:8.0 /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/libssl.so.1.1
COPY --from=mysql:8.0 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/libcrypto.so.1.1

USER keycloak