server:
  port: 8040

spring:
  application:
    name: "TEST-SERVICE"

  output:
    ansi:
      enabled: ALWAYS

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/test-realm/protocol/openid-connect/certs
#  http://localhost:8080/realms/online-store-realm/protocol/openid-connect/certs

