server:
  port: ${CART_SERVICE_PORT:0}

spring:
  application:
    name: "CART-SERVICE"

  output.ansi.enabled: ALWAYS

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/online-store-realm/protocol/openid-connect/certs

  cloud:
    loadbalancer:
      retry:
        enabled: true                        # включение повторных попыток при недоступности сервисов
      healthCheck:
        enabled: true                        # включение проверки состояния для сервисов

# настройки Эврики
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:7777/eureka
    register-with-eureka: true                # Регистрация клиента в Eureka Server
    fetch-registry: true                      # Извлечение реестра из Eureka Server
    retry-on-connect-errors: true             # Повторные подключения к Eureka при сбоях
  instance:
    prefer-ip-address: false                  # Использовать IP-адрес вместо имени хоста
    lease-renewal-interval-in-seconds: 10     # Интервал отправки heartbeats
    lease-expiration-duration-in-seconds: 30  # Таймаут для истечения lease (сердцебиений)

  # H2 database
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:magazin         # будем использовать БД в памяти.
    username: sa
    password:
  # консоль для отладки
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true      # для удаленного доступа: localhost:8090/CATALOG-SERVICE/h2-console

  # автозапуск schema.sql
  sql:
    init:
      mode: always
#      platform: mysql
  # Spring Jpa Hibernate
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: false
        format_sql: true

    generate-ddl: true
#    defer-datasource-initialization: true
#    open-in-view: false

#logging:
#  level:
#    org.springframework.security.web: DEBUG
